--
-- PostgreSQL database dump
--

\restrict s3vdHUfCMgOR9ZftUcQ7QJfkXOSJ2RnyZU8a7zJ0DYhSaMmvkq3K0D1D7wOcCwy

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg12+1)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_contactmessage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_contactmessage (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    subject character varying(200) NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_read boolean NOT NULL
);


--
-- Name: contact_contactmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_contactmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_contactmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: gallery_galleryimage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gallery_galleryimage (
    id bigint NOT NULL,
    title character varying(150) NOT NULL,
    category character varying(20) NOT NULL,
    image character varying(100),
    "order" integer NOT NULL,
    CONSTRAINT gallery_galleryimage_order_check CHECK (("order" >= 0))
);


--
-- Name: gallery_galleryimage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gallery_galleryimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_galleryimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    slug character varying(50) NOT NULL,
    short_description character varying(250) NOT NULL,
    description text NOT NULL,
    image character varying(100),
    is_featured boolean NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT products_product_order_check CHECK (("order" >= 0))
);


--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quotes_quoterequest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quotes_quoterequest (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    company character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    product character varying(40) NOT NULL,
    quantity character varying(100) NOT NULL,
    details text NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: quotes_quoterequest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quotes_quoterequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quotes_quoterequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: website_client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.website_client (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    logo character varying(100),
    "order" integer NOT NULL,
    CONSTRAINT website_client_order_check CHECK (("order" >= 0))
);


--
-- Name: website_client_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.website_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.website_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: website_manufacturingcapability; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.website_manufacturingcapability (
    id bigint NOT NULL,
    icon character varying(10) NOT NULL,
    title character varying(150) NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT website_manufacturingcapability_order_check CHECK (("order" >= 0))
);


--
-- Name: website_manufacturingcapability_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.website_manufacturingcapability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.website_manufacturingcapability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: website_manufacturingphoto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.website_manufacturingphoto (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    caption character varying(150) NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT website_manufacturingphoto_order_check CHECK (("order" >= 0))
);


--
-- Name: website_manufacturingphoto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.website_manufacturingphoto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.website_manufacturingphoto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add client	7	add_client
26	Can change client	7	change_client
27	Can delete client	7	delete_client
28	Can view client	7	view_client
29	Can add Manufacturing Capability	8	add_manufacturingcapability
30	Can change Manufacturing Capability	8	change_manufacturingcapability
31	Can delete Manufacturing Capability	8	delete_manufacturingcapability
32	Can view Manufacturing Capability	8	view_manufacturingcapability
33	Can add Manufacturing Photo	9	add_manufacturingphoto
34	Can change Manufacturing Photo	9	change_manufacturingphoto
35	Can delete Manufacturing Photo	9	delete_manufacturingphoto
36	Can view Manufacturing Photo	9	view_manufacturingphoto
37	Can add product	10	add_product
38	Can change product	10	change_product
39	Can delete product	10	delete_product
40	Can view product	10	view_product
41	Can add gallery image	11	add_galleryimage
42	Can change gallery image	11	change_galleryimage
43	Can delete gallery image	11	delete_galleryimage
44	Can view gallery image	11	view_galleryimage
45	Can add contact message	12	add_contactmessage
46	Can change contact message	12	change_contactmessage
47	Can delete contact message	12	delete_contactmessage
48	Can view contact message	12	view_contactmessage
49	Can add quote request	13	add_quoterequest
50	Can change quote request	13	change_quoterequest
51	Can delete quote request	13	delete_quoterequest
52	Can view quote request	13	view_quoterequest
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1500000$OK4WHd8of7WyMWylpzTa0R$7OJ0Ebkr0BL2r4KpndMXjNp78Lh6A3R+8N7rhj5Edlo=	2026-08-08 05:49:22.139156+00	t	admin			nblnbl224@gmail.com	t	t	2026-08-07 09:24:28.788415+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: contact_contactmessage; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.contact_contactmessage (id, name, email, phone, subject, message, created_at, is_read) FROM stdin;
1	Robertpoose	henrydixon487@gmail.com	85914187328	Hallo, i am wrote about   the price	Sawubona, bengifuna ukwazi intengo yakho.	2026-08-08 18:22:19.80547+00	f
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-07 11:36:16.153237+00	1	achar kada	1	[{"added": {}}]	7	1
2	2026-08-07 11:43:34.49676+00	2	automax	1	[{"added": {}}]	7	1
3	2026-08-07 11:45:18.543766+00	3	azzaro	1	[{"added": {}}]	7	1
4	2026-08-07 11:45:21.236309+00	4	azzaro	1	[{"added": {}}]	7	1
5	2026-08-07 11:45:22.75594+00	5	azzaro	1	[{"added": {}}]	7	1
6	2026-08-07 11:45:23.034562+00	6	azzaro	1	[{"added": {}}]	7	1
7	2026-08-07 11:45:23.642357+00	7	azzaro	1	[{"added": {}}]	7	1
8	2026-08-07 11:45:42.374492+00	7	azzaro	3		7	1
9	2026-08-07 11:45:42.374537+00	6	azzaro	3		7	1
10	2026-08-07 11:45:42.374554+00	5	azzaro	3		7	1
11	2026-08-07 11:45:42.374566+00	4	azzaro	3		7	1
12	2026-08-07 11:54:51.945473+00	1	CUSTOMIZED PAPER BAGS	1	[{"added": {}}]	10	1
13	2026-08-07 11:57:26.728525+00	2	CUSTOMIZED NON-WOVEN BAGS	1	[{"added": {}}]	10	1
14	2026-08-07 12:00:28.590215+00	3	PAPER CARRY BAGS	1	[{"added": {}}]	10	1
15	2026-08-07 12:02:16.100707+00	4	Laminated Non-woven Bags	1	[{"added": {}}]	10	1
16	2026-08-07 12:05:38.057971+00	3	PAPER CARRY BAGS	2	[{"changed": {"fields": ["Image"]}}]	10	1
17	2026-08-07 12:07:43.652706+00	1	Automated Production Line	3		11	1
18	2026-08-07 12:07:43.652761+00	2	Paper Bag Making Machine	3		11	1
19	2026-08-07 12:07:43.652783+00	3	Finished Paper Bags	3		11	1
20	2026-08-07 12:07:43.6528+00	4	Non-Woven Bag Range	3		11	1
21	2026-08-07 12:07:43.652814+00	5	Quality Check	3		11	1
22	2026-08-07 12:07:43.652829+00	6	Bulk Order Dispatch	3		11	1
23	2026-08-07 12:07:43.652843+00	7	Flexo Printing in Progress	3		11	1
24	2026-08-07 12:07:43.652856+00	8	Client Branded Bags	3		11	1
25	2026-08-07 12:12:58.778288+00	9	CARRY BAGS IN MULTIPLE COLOURS	1	[{"added": {}}]	11	1
26	2026-08-07 12:14:48.15009+00	10	CARRY BAGS V BOTTOM & SQUARE BOTTOM	1	[{"added": {}}]	11	1
27	2026-08-07 12:15:47.323294+00	10	CARRY BAGS V BOTTOM & SQUARE BOTTOM WITH PRINTING	2	[{"changed": {"fields": ["Title"]}}]	11	1
28	2026-08-07 12:19:03.936792+00	11	CARRY BAGS V BOTTOM & SQUARE BOTTOM WITHOUT PRINTING	1	[{"added": {}}]	11	1
29	2026-08-07 12:21:05.623975+00	12	CARRY BAGS PLAIN AND CUSTOMISED	1	[{"added": {}}]	11	1
61	2026-08-07 12:27:45.053807+00	44	HANDLES	1	[{"added": {}}]	11	1
62	2026-08-07 12:29:36.363274+00	45	CARRY BAGS NON WOVEN BAGS D CUT AND HANDLE	1	[{"added": {}}]	11	1
63	2026-08-07 12:31:49.052615+00	46	CARRY BAGS NON WOVEN BAGS D CUT AND HANDLE WITH PRINTING	1	[{"added": {}}]	11	1
64	2026-08-07 12:32:28.622495+00	47	GUSSET	1	[{"added": {}}]	11	1
65	2026-08-07 12:33:10.79751+00	47	GUSSET	2	[{"changed": {"fields": ["Category", "Image", "Order"]}}]	11	1
66	2026-08-07 12:34:01.241282+00	48	NON WOVEN BAGS	1	[{"added": {}}]	11	1
67	2026-08-07 12:35:07.814033+00	1	achar kada	3		7	1
68	2026-08-07 12:35:07.81408+00	2	automax	3		7	1
69	2026-08-07 12:35:07.814098+00	3	azzaro	3		7	1
70	2026-08-07 12:44:17.997863+00	1	PRAKASH AUTO 450 Paper Bag Making Machine	1	[{"added": {}}]	9	1
71	2026-08-07 12:44:56.482747+00	2	PRAKASH 360 Paper Bag Making Machine	1	[{"added": {}}]	9	1
72	2026-08-07 12:45:41.002463+00	3	PRAKASH PBM2C1517	1	[{"added": {}}]	9	1
73	2026-08-07 12:47:18.672195+00	4	PRAKASSH - 4 COLOUR FLEXO PRINTER	1	[{"added": {}}]	9	1
74	2026-08-07 12:48:37.642412+00	5	NONWOVEN Bag Making Machine	1	[{"added": {}}]	9	1
75	2026-08-07 12:52:12.689806+00	6	PRAKASH OFFSET Printing Machine	1	[{"added": {}}]	9	1
76	2026-08-07 12:53:40.630407+00	7	DIGITAL PRINT - FAIRPRINT	1	[{"added": {}}]	9	1
77	2026-08-07 12:54:45.071686+00	8	DRUM PRINT - FIVE FINGERS	1	[{"added": {}}]	9	1
78	2026-08-07 12:55:31.851394+00	9	REEL SLITTING MACHINE	1	[{"added": {}}]	9	1
79	2026-08-07 12:57:19.177033+00	8	NESTO	1	[{"added": {}}]	7	1
80	2026-08-07 12:57:43.597896+00	9	DIGITAL	1	[{"added": {}}]	7	1
81	2026-08-07 12:58:18.074199+00	9	DIGITAL FLAIR	2	[{"changed": {"fields": ["Name", "Logo", "Order"]}}]	7	1
82	2026-08-08 04:47:51.358779+00	9	DIGITAL FLAIR	3		7	1
83	2026-08-08 04:48:32.622817+00	10	Achar kada	1	[{"added": {}}]	7	1
84	2026-08-08 04:48:48.647849+00	11	Automax	1	[{"added": {}}]	7	1
85	2026-08-08 04:49:15.04802+00	12	boon	1	[{"added": {}}]	7	1
86	2026-08-08 04:49:28.155496+00	13	cochin snack	1	[{"added": {}}]	7	1
87	2026-08-08 04:49:45.582775+00	14	ea	1	[{"added": {}}]	7	1
88	2026-08-08 04:49:55.642067+00	15	jakes	1	[{"added": {}}]	7	1
89	2026-08-08 04:50:06.826434+00	16	khair allah	1	[{"added": {}}]	7	1
90	2026-08-08 04:50:25.063855+00	17	kidz	1	[{"added": {}}]	7	1
91	2026-08-08 04:50:42.627095+00	18	maharani	1	[{"added": {}}]	7	1
92	2026-08-08 04:50:59.27978+00	19	mobile tech	1	[{"added": {}}]	7	1
93	2026-08-08 04:51:17.319668+00	20	pink magic	1	[{"added": {}}]	7	1
94	2026-08-08 04:51:31.666203+00	21	tamar	1	[{"added": {}}]	7	1
95	2026-08-08 04:51:47.089972+00	22	track	1	[{"added": {}}]	7	1
96	2026-08-08 04:52:09.234109+00	23	toffee paws	1	[{"added": {}}]	7	1
97	2026-08-08 04:52:26.85781+00	24	tradelink	1	[{"added": {}}]	7	1
98	2026-08-08 04:52:46.980985+00	25	trendy	1	[{"added": {}}]	7	1
99	2026-08-08 04:53:02.267093+00	26	wonderkid	1	[{"added": {}}]	7	1
100	2026-08-08 04:53:15.735292+00	27	yello	1	[{"added": {}}]	7	1
101	2026-08-08 07:03:07.872264+00	12	boon	3		7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	website	client
8	website	manufacturingcapability
9	website	manufacturingphoto
10	products	product
11	gallery	galleryimage
12	contact	contactmessage
13	quotes	quoterequest
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-07 09:10:32.128684+00
2	auth	0001_initial	2026-08-07 09:10:32.420804+00
3	admin	0001_initial	2026-08-07 09:10:32.436897+00
4	admin	0002_logentry_remove_auto_add	2026-08-07 09:10:32.441377+00
5	admin	0003_logentry_add_action_flag_choices	2026-08-07 09:10:32.446668+00
6	contenttypes	0002_remove_content_type_name	2026-08-07 09:10:32.522691+00
7	auth	0002_alter_permission_name_max_length	2026-08-07 09:10:32.528242+00
8	auth	0003_alter_user_email_max_length	2026-08-07 09:10:32.537534+00
9	auth	0004_alter_user_username_opts	2026-08-07 09:10:32.541897+00
10	auth	0005_alter_user_last_login_null	2026-08-07 09:10:32.5481+00
11	auth	0006_require_contenttypes_0002	2026-08-07 09:10:32.549881+00
12	auth	0007_alter_validators_add_error_messages	2026-08-07 09:10:32.554333+00
13	auth	0008_alter_user_username_max_length	2026-08-07 09:10:32.562315+00
14	auth	0009_alter_user_last_name_max_length	2026-08-07 09:10:32.568419+00
15	auth	0010_alter_group_name_max_length	2026-08-07 09:10:32.618002+00
16	auth	0011_update_proxy_permissions	2026-08-07 09:10:32.623045+00
17	auth	0012_alter_user_first_name_max_length	2026-08-07 09:10:32.629735+00
18	contact	0001_initial	2026-08-07 09:10:32.635588+00
19	gallery	0001_initial	2026-08-07 09:10:32.644285+00
20	gallery	0002_seed_gallery_images	2026-08-07 09:10:32.655801+00
21	products	0001_initial	2026-08-07 09:10:32.720241+00
22	quotes	0001_initial	2026-08-07 09:10:32.725359+00
23	sessions	0001_initial	2026-08-07 09:10:32.737363+00
24	website	0001_initial	2026-08-07 09:10:32.814083+00
25	website	0002_manufacturingcapability_manufacturingphoto	2026-08-07 09:10:32.823881+00
26	website	0003_seed_manufacturing_capabilities	2026-08-07 09:10:32.836633+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
mlt551j7v4x1s2xq2z820q106dirapre	.eJxVjDEOAiEQRe9CbQggw4ClvWcgzICyaiBZdivj3XWTLbT9773_EjGtS43rKHOcsjgJLQ6_GyV-lLaBfE_t1iX3tswTyU2ROx3y0nN5nnf376CmUb-1ZQ2cTSlAZMAhgA7eW74qQMSEhrxyHOiojXZWEecclPEqhEKkHYr3B807Nxc:1wsGpd:HkIeM_Od_XytyCbfGQbMGwtImzQCzcmtdmAizmj4DA0	2026-08-21 09:25:37.822143+00
cmdxtagv7ta4y64yt71zwqamshiuozv3	.eJxVjDEOAiEQRe9CbQggw4ClvWcgzICyaiBZdivj3XWTLbT9773_EjGtS43rKHOcsjgJLQ6_GyV-lLaBfE_t1iX3tswTyU2ROx3y0nN5nnf376CmUb-1ZQ2cTSlAZMAhgA7eW74qQMSEhrxyHOiojXZWEecclPEqhEKkHYr3B807Nxc:1wsZvu:LdFEr5E2J26Z4D_3ToK4_H1VBAy_BKdEvD7FHoB0a40	2026-08-22 05:49:22.223672+00
\.


--
-- Data for Name: gallery_galleryimage; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.gallery_galleryimage (id, title, category, image, "order") FROM stdin;
9	CARRY BAGS IN MULTIPLE COLOURS	product	media/gallery/carry_bags_nyap7x	0
10	CARRY BAGS V BOTTOM & SQUARE BOTTOM WITH PRINTING	product	media/gallery/carrybagsvbottom_zkaeln	1
11	CARRY BAGS V BOTTOM & SQUARE BOTTOM WITHOUT PRINTING	product	media/gallery/CARRYBAGSWITHOUT_rb18ot	2
12	CARRY BAGS PLAIN AND CUSTOMISED	product	media/gallery/carry_bags_plain_ueancg	3
44	HANDLES	product	media/gallery/hndl_xb4zlf	4
45	CARRY BAGS NON WOVEN BAGS D CUT AND HANDLE	product	media/gallery/Carrybagsnon_eqg1jy	4
46	CARRY BAGS NON WOVEN BAGS D CUT AND HANDLE WITH PRINTING	product	media/gallery/CARRY_BAGS_IY_sh2qf6	6
47	GUSSET	product	media/gallery/GUSSET_g0go37	7
48	NON WOVEN BAGS	product	media/gallery/NONW_lfeenb	8
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products_product (id, name, slug, short_description, description, image, is_featured, "order", created_at) FROM stdin;
1	CUSTOMIZED PAPER BAGS	customized-paper-bags	Elevate your brand with premium-quality, eco-friendly paper bags designed for durability and style. Perfect for retail, boutiques, supermarkets, bakeries, and events, they offer a sustainable packaging solution that leaves a lasting impression.	Premium-quality paper bags designed to enhance brand visibility while o ering an eco-friendly packaging solution suitable for retail stores, boutiques, supermarkets, bakeries, and promotional events.\r\nmake it short description	media/products/customized_paper_bags_ioghx2	t	0	2026-08-07 11:54:51.94293+00
2	CUSTOMIZED NON-WOVEN BAGS	customized-non-woven-bags	Eco-friendly, durable, and reusable bags built to showcase your brand at shopping events, exhibitions, and promotional campaigns.	Durable, reusable, and environmentally conscious bags ideal for shopping, exhibitions, promotional campaigns, and corporate branding.	media/products/nonwovenbag_rihblt	t	1	2026-08-07 11:57:26.726326+00
4	Laminated Non-woven Bags	laminated-non-woven-bags	Stylish, eco-friendly, and ultra-durable, our laminated non-woven bags deliver a sleek, water-resistant finish ideal for elevated retail and promotional packaging.	Experience the perfect blend of style and sustainability with our laminated non-woven bags. These bags combine the durability of non-woven materials with the sleek finish of lamination, offering a chic and practical packaging solution for various retail and promotional needs.	media/products/paperbag_ncee5b	t	3	2026-08-07 12:02:16.09798+00
3	PAPER CARRY BAGS	paper-carry-bags	Versatile, heavy-duty carry bags available in multiple sizes to deliver reliable performance across all commercial uses.	Strong and reliable carry bags available in multiple sizes and specifications, suitable for a wide range of commercial applications.	media/products/pp_aqqncv	t	2	2026-08-07 12:00:28.587225+00
\.


--
-- Data for Name: quotes_quoterequest; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quotes_quoterequest (id, name, company, email, phone, product, quantity, details, status, created_at) FROM stdin;
1	Nabeel Rahman	jain	nblnbl224@gmail.com	8590784962	paper-carry-bags	4555	big	new	2026-08-08 04:55:31.470325+00
\.


--
-- Data for Name: website_client; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.website_client (id, name, logo, "order") FROM stdin;
8	NESTO	media/clients/NESTO_hxhiqz	0
10	Achar kada	media/clients/achar_kada_zt7pnl	1
11	Automax	media/clients/Automax_gdkzaw	2
13	cochin snack	media/clients/cochin_snack_mb1a3w	4
14	ea	media/clients/ea_zh1kll	4
15	jakes	media/clients/jakes_gsu9cm	5
16	khair allah	media/clients/khair_allah_ndgojd	6
17	kidz	media/clients/Kidz_bti8ui	7
18	maharani	media/clients/Maharani_tzxkbz	8
19	mobile tech	media/clients/mobile_tech_aj6qrr	8
20	pink magic	media/clients/Pink_Magic_svx0sp	9
21	tamar	media/clients/tamar_j9pvy2	10
22	track	media/clients/track_enlak7	10
23	toffee paws	media/clients/toffee_Paws_oifkef	11
24	tradelink	media/clients/tradelink_iak0bv	12
25	trendy	media/clients/trendy_a7d5ez	12
26	wonderkid	media/clients/Wonderkid_zm9ohl	13
27	yello	media/clients/yello_s8vgxe	14
\.


--
-- Data for Name: website_manufacturingcapability; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.website_manufacturingcapability (id, icon, title, "order") FROM stdin;
1	🏭	100% Automated Manufacturing Facility	1
2	📦	Production Capacity: 3,00,000 Bags per Day	2
3	🖨️	High-Speed Printing & Finishing	3
4	🌍	Premium Imported Raw Materials	4
5	✅	Strict Quality Control	5
6	🌱	Eco-Friendly Production Process	6
\.


--
-- Data for Name: website_manufacturingphoto; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.website_manufacturingphoto (id, image, caption, "order") FROM stdin;
1	media/manufacturing/prakash450_w28cxr	PRAKASH AUTO 450 Paper Bag Making Machine	0
2	media/manufacturing/PRAKASH360_uluo5d	PRAKASH 360 Paper Bag Making Machine	1
3	media/manufacturing/PRAKASHPBM2C_hmcgaw	PRAKASH PBM2C1517	2
4	media/manufacturing/PRAKASH-4_ahf0hc	PRAKASSH - 4 COLOUR FLEXO PRINTER	3
5	media/manufacturing/NON_WOVEN_kqszph	NONWOVEN Bag Making Machine	4
6	media/manufacturing/prakashoff_lmifnd	PRAKASH OFFSET Printing Machine	5
7	media/manufacturing/digitalpy_fdhual	DIGITAL PRINT - FAIRPRINT	6
8	media/manufacturing/DRUMPRINT_vvd16c	DRUM PRINT - FIVE FINGERS	7
9	media/manufacturing/REEL__ciz7uw	REEL SLITTING MACHINE	8
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: contact_contactmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contact_contactmessage_id_seq', 1, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 101, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 26, true);


--
-- Name: gallery_galleryimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.gallery_galleryimage_id_seq', 48, true);


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_product_id_seq', 4, true);


--
-- Name: quotes_quoterequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quotes_quoterequest_id_seq', 1, true);


--
-- Name: website_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.website_client_id_seq', 27, true);


--
-- Name: website_manufacturingcapability_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.website_manufacturingcapability_id_seq', 6, true);


--
-- Name: website_manufacturingphoto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.website_manufacturingphoto_id_seq', 9, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: contact_contactmessage contact_contactmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_contactmessage
    ADD CONSTRAINT contact_contactmessage_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: gallery_galleryimage gallery_galleryimage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gallery_galleryimage
    ADD CONSTRAINT gallery_galleryimage_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_slug_key UNIQUE (slug);


--
-- Name: quotes_quoterequest quotes_quoterequest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quotes_quoterequest
    ADD CONSTRAINT quotes_quoterequest_pkey PRIMARY KEY (id);


--
-- Name: website_client website_client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.website_client
    ADD CONSTRAINT website_client_pkey PRIMARY KEY (id);


--
-- Name: website_manufacturingcapability website_manufacturingcapability_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.website_manufacturingcapability
    ADD CONSTRAINT website_manufacturingcapability_pkey PRIMARY KEY (id);


--
-- Name: website_manufacturingphoto website_manufacturingphoto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.website_manufacturingphoto
    ADD CONSTRAINT website_manufacturingphoto_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: products_product_slug_70d3148d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_product_slug_70d3148d_like ON public.products_product USING btree (slug varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict s3vdHUfCMgOR9ZftUcQ7QJfkXOSJ2RnyZU8a7zJ0DYhSaMmvkq3K0D1D7wOcCwy

