# Generated by Django 6.1 on 2026-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('product', models.CharField(choices=[('customized-paper-bags', 'Customized Paper Bags'), ('customized-non-woven-bags', 'Customized Non-Woven Bags'), ('paper-carry-bags', 'Paper Carry Bags'), ('laminated-non-woven-bags', 'Laminated Non-Woven Bags'), ('other', 'Other / Not Sure')], default='other', max_length=40)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
